server:
  port: 8080

mysql:
  host: localhost
  # host: go-backend-mysql
  port: 3307
  # port: 3306
  user: root
  password: root
  dbName: IAM
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 60
  connMaxIdleTime: 60

redis:
  # host: go-backend-redis
  host: localhost
  port: 6379
  password: King_112
  db: 0
  poolSize: 20
  minIdleConns: 10
  dialTimeout: 5
  readTimeout: 3
  writeTimeout: 3
  connMaxIdleTime: 60

jwt:
  secret: "SaphaKing"
  expiration_time: "72h"

cookie:
  domain: ""
  secure: false 
  http_only: true
  same_site: "Strict"