server:
  port: 8080

mysql:
  host: localhost
  port: 3307
  user: root
  password: root
  dbName: IAM
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 60
  connMaxIdleTime: 60

redis:
  host: localhost
  port: 6379
  password: Test_112
  db: 0
  poolSize: 20
  minIdleConns: 10
  dialTimeout: 5
  readTimeout: 3
  writeTimeout: 3
  connMaxIdleTime: 60

jwt:
  secret: "SaphaKing"
  expiration_time: "72h"
  encryption_key: "MySecretEncryptionKey32BytesKey!"

cookie:
  domain: ""
  secure: false 
  http_only: true
  same_site: "Strict"

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  iam_exchange: "iam_events_topic"